// Every backend route used by the app, in one place. Paths are relative to VITE_API_BASE_URL.
// See BACKEND_API.md for request/response contracts.
export const EP = {
  auth: {
    login: '/auth/login',
    google: '/auth/google',
    register: '/auth/register',
    verifyOtp: '/auth/verify-otp',
    resendOtp: '/auth/resend-otp',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    forgotPassword: '/auth/forgot-password',
    me: '/auth/me',
  },
  dashboard: '/dashboard',
  notifications: {
    list: '/notifications',
    readAll: '/notifications/read-all',
    read: id => `/notifications/${id}/read`,
  },
  search: '/search',
  chat: {
    conversations: '/chat/conversations',
    conversation: id => `/chat/conversations/${id}`,
    messages: id => `/chat/conversations/${id}/messages`,
    pin: id => `/chat/conversations/${id}/pin`,
    feedback: id => `/chat/messages/${id}/feedback`,
    saveToVault: id => `/chat/messages/${id}/save`,
    reportSource: '/chat/sources/report',
    topics: '/chat/topics',
  },
  documents: {
    upload: '/documents',
    analyses: '/analyses',
    analysis: id => `/analyses/${id}`,
    analysisReport: id => `/analyses/${id}/report`,
    analysisShare: id => `/analyses/${id}/share`,
  },
  vault: {
    documents: '/vault/documents',
    document: id => `/vault/documents/${id}`,
    file: id => `/vault/documents/${id}/file`,
    content: id => `/vault/documents/${id}/content`,
    copy: id => `/vault/documents/${id}/copy`,
    favourite: id => `/vault/documents/${id}/favourite`,
    notes: id => `/vault/documents/${id}/notes`,
    activity: id => `/vault/documents/${id}/activity`,
    folders: '/vault/folders',
    stats: '/vault/stats',
  },
  briefs: {
    draft: '/case-briefs/draft',
    list: '/case-briefs',
    brief: id => `/case-briefs/${id}`,
    attachments: '/case-briefs/attachments',
    regenerate: id => `/case-briefs/${id}/regenerate`,
    export: id => `/case-briefs/${id}/export`,
    invites: id => `/case-briefs/${id}/invites`,
    shareLink: id => `/case-briefs/${id}/share-link`,
  },
  calculators: {
    list: '/calculators',
    calculate: type => `/calculators/${type}/calculate`,
    saved: '/calculators/saved',
    summary: id => `/calculators/saved/${id}/summary`,
  },
  legalAid: {
    providers: '/legal-aid/providers',
    saved: id => `/legal-aid/providers/${id}/save`,
    emergency: '/legal-aid/emergency-contacts',
  },
  lawyers: {
    list: '/lawyers',
    one: id => `/lawyers/${id}`,
    earnings: id => `/lawyers/${id}/earnings`,
    apply: '/lawyers/apply',
  },
  bookings: {
    list: '/bookings',
    one: id => `/bookings/${id}`,
    pay: id => `/bookings/${id}/pay`,
    mine: '/bookings/mine',
    complete: id => `/bookings/${id}/complete`,
  },
  admin: {
    stats: '/admin/stats',
    lawyers: '/admin/lawyers',
    lawyer: id => `/admin/lawyers/${id}`,
    users: '/admin/users',
    user: id => `/admin/users/${id}`,
    bookings: '/admin/bookings',
    bookingPaid: id => `/admin/bookings/${id}/paid`,
  },
  community: {
    categories: '/community/categories',
    questions: '/community/questions',
    question: id => `/community/questions/${id}`,
    answers: id => `/community/questions/${id}/answers`,
  },
  emergency: {
    categories: '/emergency/contacts',
    personalContacts: '/emergency/personal-contacts',
    personalContact: id => `/emergency/personal-contacts/${id}`,
    alert: '/emergency/alert',
  },
  offline: {
    manifest: '/offline/manifest',
    sync: '/sync',
  },
  whatsapp: {
    status: '/whatsapp',
    connect: '/whatsapp/connect',
    qr: '/whatsapp/qr',
    testMessage: '/whatsapp/test-message',
    commands: '/whatsapp/commands',
    disconnect: '/whatsapp',
  },
  settings: {
    profile: '/users/me',
    avatar: '/users/me/avatar',
    password: '/users/me/password',
    security: '/users/me/security',
    sessions: '/users/me/sessions',
    session: id => `/users/me/sessions/${id}`,
    preferences: '/users/me/preferences',
    export: '/users/me/export',
    account: '/users/me',
    integrations: '/users/me/integrations',
    integration: provider => `/users/me/integrations/${provider}`,
  },
}
